### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by Fristi** [fs2-blobstore/fs2-blobstore#330] opened 2021-03-08 13:49 UTC
Would it be possible to support batch operations, we now have a case where we upload ~1600 individual files of 2 kilobytes which is a bit slow.

- Do existing http 1.x apis support this
- Would it work over http2 ? 
- What stores would suppor this?

**Comment by jgogstad** [comment] 2021-03-10 22:15
I think @gafiatulin looked into this at some point. From my point of view:

> • Do existing http 1.x apis support this

Only in the sense that you would open multiple HTTP connections, keep them in a pool, and use those for transferring files in parallel. HTTP doesn't support multiple parallel requests on a single connection.

> • Would it work over http2 ?
> • What stores would suppor this?

Probably, but it would need to be supported on the other end of course. I don't know if any of the cloud providers support this, it would need some investigation.

For your usecase, you probably want to model one upload per file and then run those in parallel. Something along the lines of

```scala
import blobstore.PathOps._
import squants.information.Mebibytes

val store: Store[IO] = ???
val dest: Store[IO] = ???
  
store.list(Path("foo"))
  .map(p => store.get(p, Mebibytes(2).toBytes.toInt).through(dest.put(Path("bar") / p)))
  .parJoin(maxOpen = 500)
// or
//  .parJoinUnbounded 
```

Off the top of my head, GCS by default doesn't do any connection pooling and S3 does. You can configure connection pools using the cloud native APIs (e.g. `S3AsyncClient` or `com.google.cloud.storage.Storage`). Just make sure to keep some parity between the size of the connection pool and the number of threads/fibers you use for executing requests.

**Comment by gafiatulin** [comment] 2021-03-11 01:53
In supporting batch operation we are limited to what each specific service provides. 

**GCS**
As of right now GCS only supports batching of getting/setting metadata and delete operations. It is possible to have multiple operations and multiple targets per operation batched into a single request. Batching of upload/download operations is not supported.
[Documentation](https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch), [API Reference](https://googleapis.dev/java/google-cloud-storage/latest/com/google/cloud/storage/StorageBatch.html)

**S3**
S3 supports modifying metadata (or closely related operations like restore from Glacier or invoking Lambda) + copy. Difference with GCS here is that S3 batches are _homogeneous_ – each request has only one operation type and batching is happening only in terms of operation targets. Also no support for upload/download.
[Documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops.html), [API Reference](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3control/model/JobOperation.html)

**Azure**
Azure Storage currently supports only delete and set tier operations for batching. Here batches are also _homogeneous_.
[Documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch), [API Reference](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-storage-blob-batch/12.7.0/index.html)

**SFTP** and **Box** don't have support for batch operations. 

It shouldn't be that hard to add support for batching to `Store`s where underlying service supports it. But that wouldn't help you with your problem.

----

Depending on the storage system and client configuration it might already be possible to use HTTP2. It is likely to improve performance as single connection would be reused with request-response multiplexing, lower protocol overhead and binary frames. Although that would technically not be batching – still separate requests, just with lower overhead per request on the protocol level. 

That should give performance boost, I'm not sure how big, but might be enough to make timing more manageable for you.

Still it is likely that small files would still have worse performance than bigger ones. The problem is that all these blob stores are really strong in terms of single stream throughput, but there’s a fixed latency cost per logical request that’s related to ensuring that the files are replicated and uploaded properly.

----

As @jgogstad said doing parallel (via FS2's `parJoin` or `parEvalMapUnordered`, etc) uploads would be the first step, if you are not already doing that. 

If you are already doing parallelism and it is still slow there might be some tricks you can try. For example tweak file naming convention or shuffle order so that names are distributed better or do gradual ramp up [[1]](https://jbrojbrojbro.medium.com/your-sequentially-named-files-are-slowing-down-your-uploads-601e77af63ec), [[2]](https://cloud.google.com/storage/docs/request-rate#naming-convention), [[3]](https://aws.amazon.com/premiumsupport/knowledge-center/s3-object-key-naming-pattern/). 

----

It would be helpful if you can share:
1. Which storage service you are using
2. How you create the client 
3. How you invoke the uploads (parallel or not)
4. If you are doing something custom when creating `ContextShift[F]` and `Blocker`

**Comment by Fristi** [comment] 2021-03-11 10:04
Thank you @jgogstad  and @gafiatulin  for your extensive answers!

I think this is a good topic for future reference or improvements 👍🏻  

Coming back to your feedback and questions

- I am already using `parJoin` for parallel uploading files 
- I'm using `AzureStore` for storing the files
- Creating the client like this: `AzureStore(new BlobServiceClientBuilder().connectionString(config.connectionString).buildAsyncClient())`

**Comment by gafiatulin** [comment] 2021-03-11 10:26
@Fristi thank you for providing this information. I'm less familiar with Azure than GCS or S3, so it is possible that something is wrong with the implementation. 

I'll try to find some time to replicate and see if there are any code changes or configuration tuning that might improve things.

**Comment by gafiatulin** [comment] 2021-06-23 16:45
@Fristi fyi #441

**Comment by Fristi** [comment] 2021-06-23 17:12
Interesting ! Thanks for the mention

**Closed** 2022-07-20 10:15 UTC
